scripts: Include support for .bin file if .img files are not found [2/2]
* Add support for checking .bin files if .img files are not found.
* Some devices, like MTK-based ones, use .bin files for some partitions instead of .img files.
* This change ensures that the function can find the necessary files for all A/B partitions.

Change-Id: I0626c653818e849941865cefdd8a42a8ca380438
Signed-off-by: Tkpointz <pointzztk@gmail.com>

diff --git a/scripts/brillo_update_payload b/scripts/brillo_update_payload
--- a/scripts/brillo_update_payload
+++ b/scripts/brillo_update_payload
@@ -474,10 +474,18 @@ extract_partition_brillo() {
     if unzip -l "${image}" "${path}/${part}.img" >/dev/null; then
       path_in_zip="${path}"
       break
+    elif unzip -l "${image}" "${path}/${part}.bin" >/dev/null; then
+      path_in_zip="${path}"
+      break
     fi
   done
-  [[ -n "${path_in_zip}" ]] || die "Failed to find ${part}.img"
-  extract_file "${image}" "${path_in_zip}/${part}.img" "${part_file}"
+  [[ -n "${path_in_zip}" ]] || die "Failed to find ${part}.img or ${part}.bin"
+
+  if unzip -l "${image}" "${path_in_zip}/${part}.img" >/dev/null; then
+    extract_file "${image}" "${path_in_zip}/${part}.img" "${part_file}"
+  elif unzip -l "${image}" "${path_in_zip}/${part}.bin" >/dev/null; then
+    extract_file "${image}" "${path_in_zip}/${part}.bin" "${part_file}"
+  fi
 
   # If the partition is stored as an Android sparse image file, we need to
   # convert them to a raw image for the update.
